### ISSUE TITLE
add a new feature of leaderboard in the website to display all the coding contests results on acm-website

### ISSUE THREAD

**Issue by pccoe-acm** [pccoe-acm-hacktoberfest-2023/pccoeacm-website#8]
Various Coding Competitions are conducted by ACM STUDENT CHAPTER PCCOE on regular basis . So to display the Results we need a leaderboard for the same . 
Make sure you design the leaderboard similar to the color pallete used in website so that the Ui looks good and matches with the theme

**Comment by gautamb02** [comment]
Assign this to me

**Comment by pccoe-acm** [comment]
@gautam-bhagat  ok i have assigned it to you once done attach screen shot or video with your PR
